# Header
menu:
  Home: /
  Archives: /archives
  Wiki: https://grayoxygen.github.io/ShineOxygenWiki
  About Me: /about
  SiteMap: /sitemap.xml
  订阅RSS: /atom.xml

# Content
excerpt_link: 文章详细
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- weibo
# - links

# Links
# links:
  # 主题作者: http://xiguabaobao.com
  # 热前端: http://reqianduan.com

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: shineoxygen
# Baidu share
baidushare: true
 